"""empty message

Revision ID: 002b130d8993
Revises: 15d963629be6
Create Date: 2019-07-14 00:38:27.076248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002b130d8993'
down_revision = '15d963629be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spells', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spells', 'level')
    # ### end Alembic commands ###
