"""empty message

Revision ID: 3df819dd47d1
Revises: 
Create Date: 2019-07-14 00:13:06.327325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df819dd47d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ritual', sa.Boolean(), nullable=True),
    sa.Column('concentration', sa.Boolean(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('casting_time', sa.String(), nullable=True),
    sa.Column('components', sa.String(), nullable=True),
    sa.Column('spell_range', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spells')
    # ### end Alembic commands ###
