"""empty message

Revision ID: 4da244862b0e
Revises: 5666ee1d0743
Create Date: 2019-08-15 00:51:49.898947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da244862b0e'
down_revision = '5666ee1d0743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('ritual', sa.Boolean(), nullable=True),
    sa.Column('concentration', sa.Boolean(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('casting_time', sa.String(), nullable=True),
    sa.Column('components', sa.String(), nullable=True),
    sa.Column('spell_range', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('spells', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('spells', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spells', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('spells', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('custom_spells')
    # ### end Alembic commands ###
