"""empty message

Revision ID: 874e9bc3a959
Revises: 4da244862b0e
Create Date: 2019-08-15 16:43:41.242369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874e9bc3a959'
down_revision = '4da244862b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spellbooks', sa.Column('custom_spells', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spellbooks', 'custom_spells')
    # ### end Alembic commands ###
